/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author daiyd
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
        int limite = 368;
        int x1=0;
        int x2=0;
        int x3=0;
    public Panel() {
        initComponents();
    }
    public void corredor1(Ventana v){
        Corredor hilo1 = new Corredor(this,1,v);
        hilo1.start();
    }
    public void corredor2(Ventana v){
        Corredor hilo2 = new Corredor(this,2,v);
        hilo2.start();
    }
    public void corredor3(Ventana v){
        Corredor hilo3 = new Corredor(this,3,v);
        hilo3.start();
    }
    public void reset(Ventana v){
        Corredor reset = new Corredor(this,4,v);
        reset.start();
    }
    public void jugar(Ventana v){
        reset(v);
        corredor1(v);
        corredor2(v);
        corredor3(v);
    }
@Override
public void paint(Graphics g){
    super.paint(g);
    g.setColor(Color.red);
    g.fillRect(0, 30, 30, 40);
    g.setColor(Color.white);
    g.fillOval(x1, 33, 30, 30);
    
    g.setColor(Color.BLUE);
    g.fillRect(0, 120, 30, 40);
    g.setColor(Color.YELLOW);
    g.fillOval(x2, 123, 30, 30);
    
    g.setColor(Color.BLACK);
    g.fillRect(0, 210, 30, 40);
    g.setColor(Color.GREEN);
    g.fillOval(x3, 213, 30, 30);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
